name: Publish
on:
  push:
    tags: [ 'v[0-9]+\.[0-9]+.*' ]

jobs:
  build:
    uses: ./.github/workflows/ci.yml

  publish:
    needs: build
    runs-on: ubuntu-22.04
    environment:
      name: release
      url: https://pypi.org/p/ft-scikit-optimize
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: package

      - name: Publish 📦 on PyPI Test
        uses: pypa/gh-action-pypi-publish@1.8.11
        with:
          repository-url: https://test.pypi.org/legacy/


  docs:
    needs: build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [ 3.11 ]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: docs

      - name: Publish docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_DOCS_TOKEN }}
        run: |
          .github/scripts/publish_docs.sh doc/_build/html/stable
